name: pytest
on: workflow_dispatch

jobs:
  
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v4
      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest
